name: Deploy to S3

on:
  push:
    branches:
      - main  # Change to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AKIAS2VS4H5LBIZPQAFB }}
        aws-secret-access-key: ${{ secrets.jy4nmF4UxAbjUWGVW2+MlMQeSYaLm1VaY06M36K5 }}
        aws-region: us-east-1  # Change to your AWS region

    - name: Deploy to S3
      run: aws s3 sync . s3://sayudag --delete
